//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Generaciya8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Настр.
    /// </summary>
    // *** Start programmer edit section *** (настр CustomAttributes)

    // *** End programmer edit section *** (настр CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("настрE", new string[] {
            "опр as \'Опр\'",
            "опр.имя as \'Имя\'"}, Hidden=new string[] {
            "опр.имя"})]
    [AssociatedDetailViewAttribute("настрE", "содер", "содерE", true, "", "Содер", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("настрE", "опр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "имя")]
    [View("настрL", new string[] {
            "опр.имя as \'Имя\'"})]
    public class настр : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Generaciya8.опр fопр;
        
        private IIS.Generaciya8.DetailArrayOfсодер fсодер;
        
        // *** Start programmer edit section *** (настр CustomMembers)

        // *** End programmer edit section *** (настр CustomMembers)

        
        /// <summary>
        /// Настр.
        /// </summary>
        // *** Start programmer edit section *** (настр.опр CustomAttributes)

        // *** End programmer edit section *** (настр.опр CustomAttributes)
        [PropertyStorage(new string[] {
                "опр"})]
        [NotNull()]
        public virtual IIS.Generaciya8.опр опр
        {
            get
            {
                // *** Start programmer edit section *** (настр.опр Get start)

                // *** End programmer edit section *** (настр.опр Get start)
                IIS.Generaciya8.опр result = this.fопр;
                // *** Start programmer edit section *** (настр.опр Get end)

                // *** End programmer edit section *** (настр.опр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (настр.опр Set start)

                // *** End programmer edit section *** (настр.опр Set start)
                this.fопр = value;
                // *** Start programmer edit section *** (настр.опр Set end)

                // *** End programmer edit section *** (настр.опр Set end)
            }
        }
        
        /// <summary>
        /// Настр.
        /// </summary>
        // *** Start programmer edit section *** (настр.содер CustomAttributes)

        // *** End programmer edit section *** (настр.содер CustomAttributes)
        public virtual IIS.Generaciya8.DetailArrayOfсодер содер
        {
            get
            {
                // *** Start programmer edit section *** (настр.содер Get start)

                // *** End programmer edit section *** (настр.содер Get start)
                if ((this.fсодер == null))
                {
                    this.fсодер = new IIS.Generaciya8.DetailArrayOfсодер(this);
                }
                IIS.Generaciya8.DetailArrayOfсодер result = this.fсодер;
                // *** Start programmer edit section *** (настр.содер Get end)

                // *** End programmer edit section *** (настр.содер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (настр.содер Set start)

                // *** End programmer edit section *** (настр.содер Set start)
                this.fсодер = value;
                // *** Start programmer edit section *** (настр.содер Set end)

                // *** End programmer edit section *** (настр.содер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "настрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View настрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("настрE", typeof(IIS.Generaciya8.настр));
                }
            }
            
            /// <summary>
            /// "настрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View настрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("настрL", typeof(IIS.Generaciya8.настр));
                }
            }
        }
    }
}
