//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Generaciya8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Опр.
    /// </summary>
    // *** Start programmer edit section *** (опр CustomAttributes)

    // *** End programmer edit section *** (опр CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("опрE", new string[] {
            "имя as \'Имя\'"})]
    [View("опрL", new string[] {
            "имя as \'Имя\'"})]
    public class опр : ICSSoft.STORMNET.DataObject
    {
        
        private string fимя;
        
        // *** Start programmer edit section *** (опр CustomMembers)

        // *** End programmer edit section *** (опр CustomMembers)

        
        /// <summary>
        /// имя.
        /// </summary>
        // *** Start programmer edit section *** (опр.имя CustomAttributes)

        // *** End programmer edit section *** (опр.имя CustomAttributes)
        [StrLen(255)]
        public virtual string имя
        {
            get
            {
                // *** Start programmer edit section *** (опр.имя Get start)

                // *** End programmer edit section *** (опр.имя Get start)
                string result = this.fимя;
                // *** Start programmer edit section *** (опр.имя Get end)

                // *** End programmer edit section *** (опр.имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (опр.имя Set start)

                // *** End programmer edit section *** (опр.имя Set start)
                this.fимя = value;
                // *** Start programmer edit section *** (опр.имя Set end)

                // *** End programmer edit section *** (опр.имя Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "опрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View опрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("опрE", typeof(IIS.Generaciya8.опр));
                }
            }
            
            /// <summary>
            /// "опрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View опрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("опрL", typeof(IIS.Generaciya8.опр));
                }
            }
        }
    }
}
