//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Generaciya8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Содер.
    /// </summary>
    // *** Start programmer edit section *** (содер CustomAttributes)

    // *** End programmer edit section *** (содер CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("содерE", new string[] {
            "воп as \'Воп\'",
            "во1 as \'Во1\'",
            "во2 as \'Во2\'",
            "во3 as \'Во3\'"})]
    public class содер : ICSSoft.STORMNET.DataObject
    {
        
        private string fвоп;
        
        private string fво1;
        
        private string fво2;
        
        private string fво3;
        
        private IIS.Generaciya8.настр fнастр;
        
        // *** Start programmer edit section *** (содер CustomMembers)

        // *** End programmer edit section *** (содер CustomMembers)

        
        /// <summary>
        /// во1.
        /// </summary>
        // *** Start programmer edit section *** (содер.во1 CustomAttributes)

        // *** End programmer edit section *** (содер.во1 CustomAttributes)
        [StrLen(255)]
        public virtual string во1
        {
            get
            {
                // *** Start programmer edit section *** (содер.во1 Get start)

                // *** End programmer edit section *** (содер.во1 Get start)
                string result = this.fво1;
                // *** Start programmer edit section *** (содер.во1 Get end)

                // *** End programmer edit section *** (содер.во1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (содер.во1 Set start)

                // *** End programmer edit section *** (содер.во1 Set start)
                this.fво1 = value;
                // *** Start programmer edit section *** (содер.во1 Set end)

                // *** End programmer edit section *** (содер.во1 Set end)
            }
        }
        
        /// <summary>
        /// во2.
        /// </summary>
        // *** Start programmer edit section *** (содер.во2 CustomAttributes)

        // *** End programmer edit section *** (содер.во2 CustomAttributes)
        [StrLen(255)]
        public virtual string во2
        {
            get
            {
                // *** Start programmer edit section *** (содер.во2 Get start)

                // *** End programmer edit section *** (содер.во2 Get start)
                string result = this.fво2;
                // *** Start programmer edit section *** (содер.во2 Get end)

                // *** End programmer edit section *** (содер.во2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (содер.во2 Set start)

                // *** End programmer edit section *** (содер.во2 Set start)
                this.fво2 = value;
                // *** Start programmer edit section *** (содер.во2 Set end)

                // *** End programmer edit section *** (содер.во2 Set end)
            }
        }
        
        /// <summary>
        /// во3.
        /// </summary>
        // *** Start programmer edit section *** (содер.во3 CustomAttributes)

        // *** End programmer edit section *** (содер.во3 CustomAttributes)
        [StrLen(255)]
        public virtual string во3
        {
            get
            {
                // *** Start programmer edit section *** (содер.во3 Get start)

                // *** End programmer edit section *** (содер.во3 Get start)
                string result = this.fво3;
                // *** Start programmer edit section *** (содер.во3 Get end)

                // *** End programmer edit section *** (содер.во3 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (содер.во3 Set start)

                // *** End programmer edit section *** (содер.во3 Set start)
                this.fво3 = value;
                // *** Start programmer edit section *** (содер.во3 Set end)

                // *** End programmer edit section *** (содер.во3 Set end)
            }
        }
        
        /// <summary>
        /// воп.
        /// </summary>
        // *** Start programmer edit section *** (содер.воп CustomAttributes)

        // *** End programmer edit section *** (содер.воп CustomAttributes)
        [StrLen(255)]
        public virtual string воп
        {
            get
            {
                // *** Start programmer edit section *** (содер.воп Get start)

                // *** End programmer edit section *** (содер.воп Get start)
                string result = this.fвоп;
                // *** Start programmer edit section *** (содер.воп Get end)

                // *** End programmer edit section *** (содер.воп Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (содер.воп Set start)

                // *** End programmer edit section *** (содер.воп Set start)
                this.fвоп = value;
                // *** Start programmer edit section *** (содер.воп Set end)

                // *** End programmer edit section *** (содер.воп Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Generaciya8.настр.
        /// </summary>
        // *** Start programmer edit section *** (содер.настр CustomAttributes)

        // *** End programmer edit section *** (содер.настр CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "настр"})]
        public virtual IIS.Generaciya8.настр настр
        {
            get
            {
                // *** Start programmer edit section *** (содер.настр Get start)

                // *** End programmer edit section *** (содер.настр Get start)
                IIS.Generaciya8.настр result = this.fнастр;
                // *** Start programmer edit section *** (содер.настр Get end)

                // *** End programmer edit section *** (содер.настр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (содер.настр Set start)

                // *** End programmer edit section *** (содер.настр Set start)
                this.fнастр = value;
                // *** Start programmer edit section *** (содер.настр Set end)

                // *** End programmer edit section *** (содер.настр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "содерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View содерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("содерE", typeof(IIS.Generaciya8.содер));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of содер.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfсодер CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfсодер CustomAttributes)
    public class DetailArrayOfсодер : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Generaciya8.DetailArrayOfсодер members)

        // *** End programmer edit section *** (IIS.Generaciya8.DetailArrayOfсодер members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type содер by index.
        /// </summary>
        /// <summary>
        /// Adds object with type содер.
        /// </summary>
        public DetailArrayOfсодер(IIS.Generaciya8.настр fнастр) : 
                base(typeof(содер), ((ICSSoft.STORMNET.DataObject)(fнастр)))
        {
        }
        
        public IIS.Generaciya8.содер this[int index]
        {
            get
            {
                return ((IIS.Generaciya8.содер)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Generaciya8.содер dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
