//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Generaciya8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сп.
    /// </summary>
    // *** Start programmer edit section *** (сп CustomAttributes)

    // *** End programmer edit section *** (сп CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("спE", new string[] {
            "Сотр as \'Сотр\'",
            "Сотр.имя as \'Имя\'"}, Hidden=new string[] {
            "Сотр.имя"})]
    [MasterViewDefineAttribute("спE", "Сотр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "имя")]
    public class сп : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Generaciya8.Сотр fСотр;
        
        private IIS.Generaciya8.форми fформи;
        
        // *** Start programmer edit section *** (сп CustomMembers)

        // *** End programmer edit section *** (сп CustomMembers)

        
        /// <summary>
        /// Сп.
        /// </summary>
        // *** Start programmer edit section *** (сп.Сотр CustomAttributes)

        // *** End programmer edit section *** (сп.Сотр CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотр"})]
        [NotNull()]
        public virtual IIS.Generaciya8.Сотр Сотр
        {
            get
            {
                // *** Start programmer edit section *** (сп.Сотр Get start)

                // *** End programmer edit section *** (сп.Сотр Get start)
                IIS.Generaciya8.Сотр result = this.fСотр;
                // *** Start programmer edit section *** (сп.Сотр Get end)

                // *** End programmer edit section *** (сп.Сотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (сп.Сотр Set start)

                // *** End programmer edit section *** (сп.Сотр Set start)
                this.fСотр = value;
                // *** Start programmer edit section *** (сп.Сотр Set end)

                // *** End programmer edit section *** (сп.Сотр Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Generaciya8.форми.
        /// </summary>
        // *** Start programmer edit section *** (сп.форми CustomAttributes)

        // *** End programmer edit section *** (сп.форми CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "форми"})]
        public virtual IIS.Generaciya8.форми форми
        {
            get
            {
                // *** Start programmer edit section *** (сп.форми Get start)

                // *** End programmer edit section *** (сп.форми Get start)
                IIS.Generaciya8.форми result = this.fформи;
                // *** Start programmer edit section *** (сп.форми Get end)

                // *** End programmer edit section *** (сп.форми Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (сп.форми Set start)

                // *** End programmer edit section *** (сп.форми Set start)
                this.fформи = value;
                // *** Start programmer edit section *** (сп.форми Set end)

                // *** End programmer edit section *** (сп.форми Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "спE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View спE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("спE", typeof(IIS.Generaciya8.сп));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of сп.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfсп CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfсп CustomAttributes)
    public class DetailArrayOfсп : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Generaciya8.DetailArrayOfсп members)

        // *** End programmer edit section *** (IIS.Generaciya8.DetailArrayOfсп members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type сп by index.
        /// </summary>
        /// <summary>
        /// Adds object with type сп.
        /// </summary>
        public DetailArrayOfсп(IIS.Generaciya8.форми fформи) : 
                base(typeof(сп), ((ICSSoft.STORMNET.DataObject)(fформи)))
        {
        }
        
        public IIS.Generaciya8.сп this[int index]
        {
            get
            {
                return ((IIS.Generaciya8.сп)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Generaciya8.сп dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
