//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Generaciya8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Форми.
    /// </summary>
    // *** Start programmer edit section *** (форми CustomAttributes)

    // *** End programmer edit section *** (форми CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("формиE", new string[] {
            "код as \'Код\'",
            "опр as \'Опр\'",
            "опр.имя as \'Имя\'"}, Hidden=new string[] {
            "опр.имя"})]
    [AssociatedDetailViewAttribute("формиE", "сп", "спE", true, "", "Сп", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("формиE", "опр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "имя")]
    [View("формиL", new string[] {
            "код as \'Код\'",
            "опр.имя as \'Имя\'"})]
    public class форми : ICSSoft.STORMNET.DataObject
    {
        
        private int fкод;
        
        private IIS.Generaciya8.опр fопр;
        
        private IIS.Generaciya8.DetailArrayOfсп fсп;
        
        // *** Start programmer edit section *** (форми CustomMembers)

        // *** End programmer edit section *** (форми CustomMembers)

        
        /// <summary>
        /// код.
        /// </summary>
        // *** Start programmer edit section *** (форми.код CustomAttributes)

        // *** End programmer edit section *** (форми.код CustomAttributes)
        public virtual int код
        {
            get
            {
                // *** Start programmer edit section *** (форми.код Get start)

                // *** End programmer edit section *** (форми.код Get start)
                int result = this.fкод;
                // *** Start programmer edit section *** (форми.код Get end)

                // *** End programmer edit section *** (форми.код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (форми.код Set start)

                // *** End programmer edit section *** (форми.код Set start)
                this.fкод = value;
                // *** Start programmer edit section *** (форми.код Set end)

                // *** End programmer edit section *** (форми.код Set end)
            }
        }
        
        /// <summary>
        /// Форми.
        /// </summary>
        // *** Start programmer edit section *** (форми.опр CustomAttributes)

        // *** End programmer edit section *** (форми.опр CustomAttributes)
        [PropertyStorage(new string[] {
                "опр"})]
        [NotNull()]
        public virtual IIS.Generaciya8.опр опр
        {
            get
            {
                // *** Start programmer edit section *** (форми.опр Get start)

                // *** End programmer edit section *** (форми.опр Get start)
                IIS.Generaciya8.опр result = this.fопр;
                // *** Start programmer edit section *** (форми.опр Get end)

                // *** End programmer edit section *** (форми.опр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (форми.опр Set start)

                // *** End programmer edit section *** (форми.опр Set start)
                this.fопр = value;
                // *** Start programmer edit section *** (форми.опр Set end)

                // *** End programmer edit section *** (форми.опр Set end)
            }
        }
        
        /// <summary>
        /// Форми.
        /// </summary>
        // *** Start programmer edit section *** (форми.сп CustomAttributes)

        // *** End programmer edit section *** (форми.сп CustomAttributes)
        public virtual IIS.Generaciya8.DetailArrayOfсп сп
        {
            get
            {
                // *** Start programmer edit section *** (форми.сп Get start)

                // *** End programmer edit section *** (форми.сп Get start)
                if ((this.fсп == null))
                {
                    this.fсп = new IIS.Generaciya8.DetailArrayOfсп(this);
                }
                IIS.Generaciya8.DetailArrayOfсп result = this.fсп;
                // *** Start programmer edit section *** (форми.сп Get end)

                // *** End programmer edit section *** (форми.сп Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (форми.сп Set start)

                // *** End programmer edit section *** (форми.сп Set start)
                this.fсп = value;
                // *** Start programmer edit section *** (форми.сп Set end)

                // *** End programmer edit section *** (форми.сп Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "формиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View формиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("формиE", typeof(IIS.Generaciya8.форми));
                }
            }
            
            /// <summary>
            /// "формиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View формиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("формиL", typeof(IIS.Generaciya8.форми));
                }
            }
        }
    }
}
